#!/usr/bin/env bash
domain="$1"; subdomain="$2";
subs=("www" "web-01" "web-02" "lb-01")

printer(){
    echo -e "The subdomain $1 is a $2 record and points to $3"
}
info(){
    FQDN="$1"; SUBDOMAIN="$2";
    ANSWER=$(dig "${FQDN}" | grep -A1 'ANSWER SECTION:' | awk 'NR>1');
    RECORD_TYPE=$(echo "${ANSWER}" | awk '{print $4}');
    DESTINATION=$(echo "${ANSWER}" | awk '{print $5}');
    printer "$SUBDOMAIN" "$RECORD_TYPE" "$DESTINATION";
}


if ( -z "subdomain" ); then
    for sub in "${subs[@]}"; do
        info "${domain}" "${sub}"
    done
else
    info "${domain}" "${subdomain}"
fi
