#!/usr/bin/env bash
# Display domain info in of a specific sub-domain
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

domain="$1"; subdomain="$2";
subs=("www" "lb-01" "web-01" "web-02")

# print the results to stdout
displayResults () {
    echo -e "The subdomain $1 is a $2 record and points to $3"
}

# dig the domain info
getInfo () {
    FQDN="$1"; SUBDOMAIN="$2";
    ANSWER=$(dig "${FQDN}" | grep -A1 'ANSWER SECTION:' | awk 'NR>1');
    RECORD_TYPE=$(echo "${ANSWER}" | awk '{print $4}');
    DESTINATION=$(echo "${ANSWER}" | awk '{print $5}');
    displayResults "$SUBDOMAIN" "$RECORD_TYPE" "$DESTINATION";
}

# check
if ( -z "subdomain" ); then
    for sub in "${subs[@]}"; do
        info "${domain}" "${sub}"
    done
else
    info "${domain}" "${subdomain}"
fi
