#!/usr/bin/env bash
#transfair file to server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /user/share/nginx/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index*html
sudo service nginx start
