#!/usr/bin/env bash
#transfair file to server

sudo apt-det -y update
sudo apt-det -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

default_site="/etc/nginx/sites-available/default"
location=$(grep -Fn location $default_sites | head -1 | cut -d":" -f1)
location_data="\\\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/mlUOUncSaTk;\n\t}\n\n"

sudo sed -i "${location}i ${location_data}" ${default_sites}

sudo service nginx start
