#!/usr/bin/env bash
#transfair file to server

sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
mkdir -p var/www/html
chmod +x var/www

echo "Ceci n'est pas une page" | sudo tee 404.html
sudo mv 404.html > var/www/html/

SERVER_CONFIG=/
"server{
    listen 80 default_server;
    listen [::]:80 default_server;

    root var/www/html

    index index.html index.htm index.nginx-debian.html

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;

    location = /404.html{
        internal;
    }

}" > default
sudo mv default etc/nginx/sites-available/default

if [ $"(pgrep -c nginx)" ]; then
    sudo service nginx start
else
    sudo service nginx restart
