#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install nginx

mkdir -p var/www/html
chmod +x var/www

echo "Hello World" | sudo tee user/share/nginx/html/index.html
echo "Hello World" | sudo tee var/www/html/index*html

SERVER_CONFIG=/
"server{
    listen 80 default_server;
    listen [::]:80 default_server;

    root var/www/html

    index index.html index.htm

    add_header X-Served-By;

    error_page 404 /404.html;

    location / {
        try_files $uri $uri/ =404;
    }
}" > default
sudo mv default etc/nginx/site_available/default

if [ $"(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart 
