#!/usr/bin/env bash

sudo apt-get update

sudo apt-get install haproxy -y

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 432681-web-01 100.26.17.200:80 check
    server 432681-web-02 54.157.186.19:80 check
EOT

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo systemctl start haproxy

sudo systemctl enable haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
