#!/usr/bin/env bash

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 26071-web-01 44.210.150.159:80 check
    server 26071-web-02 35.173.47.15:80 check
"
sudo apt-get -y update
sudo apt-get -y upgrade


sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

sudo apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
