#!/usr/bin/env bash
# This script is displaying 
# Function to handle SIGTERM signal
sigterm_handler() {
    echo "I am invincible!!!"
}

trap 'sigterm_handler' SIGTERM

while :
do
    echo "To infinity and beyond"
    sleep 2  
done
