#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=0
while [ $i -le 12 ]
do
    echo "hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
done
