#!/usr/bin/env bash

sudo apt-get -y update

sudo echo "IPV6=yes" | sudo tee /etc/default/ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw app list
sudo ufw allow OpenSSH
sudo ufw allow ssh
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw allow 2222
sudo ufw show added
sudo ufw enable
sudo ufw allow 6000:6007/tcp
sudo ufw allow 6000:6007/udp

sudo service ufw restart
