#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get install ufw

sudo echo "IPV6=yes" | sudo tee /etc/default/ufw

sudo ufw enable -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw app list
sudo ufw allow OpenSSH
sudo ufw allow ssh
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 2222/tcp
sudo ufw show added

sudo service ufw restart
